version: '3.8'

services:
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq
    ports:
      - "6883:1883"
      - "8000:8000"

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: iotdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8432:5432"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml
      - ./logs:/var/log/nodejs
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  grafana-data:


#  docker run -d --name=promtail --volume="C:\Users\prasshre\Documents\dev\CORP0701\Project-1.06-Infrastructure\logs:/var/logs" --volume="C:\Users\prasshre\Documents\dev\CORP0701\Project-1.06-Infrastructure\promtail-config.yml:/etc/promtail/config.yml" grafana/promtail:latest --config.file=/etc/promtail/config.yml