auth_enabled: false

server:
  http_listen_port: 3100

scrape_configs:
- job_name: nodejs
  static_configs:
  - targets:
      - localhost
    labels:
      job: nodejs
      __path__: /var/log/nodejs/*log
