server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:/path/to/your/logs/positions.yaml

clients:
  - url: http://172.18.0.3:3100/loki/api/v1/push

scrape_configs:
  - job_name: node
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: C:\Users\prasshre\Documents\dev\CORP0701\Project-1.06-Infrastructure\logs\*.log
